#!/usr/bin/env python3
"""Generate web/examples.js from data/dataset_unique.jsonl.

Selects the top-N workout titles (by recorded count) among rows whose
'machines' field indicates the workout applies to RowErg (i.e.
'RowErg and SkiErg' or 'All Machines' -- excluding rows scoped only to
'BikeErg'), and writes them as a JS array literal to web/examples.js
for the static web demo's example chips.

Usage:
    python web/build_examples.py
        [--dataset data/dataset_unique.jsonl] [--out web/examples.js] [-n 8]

Run this whenever data/dataset_unique.jsonl changes; the output file
is committed (it's a tiny, deterministic artifact, and the GitHub
Pages workflow does not regenerate it).
"""

from __future__ import annotations

import argparse
import json
import os

_ROWERG_MACHINES = {"RowErg and SkiErg", "All Machines"}

_DEFAULT_DATASET = os.path.join("data", "dataset_unique.jsonl")
_DEFAULT_OUT = os.path.join("web", "examples.js")

# Hand-curated examples showcasing session workouts (warm-up + N x WORK/REST
# sets + cool-down, and long explicit interval chains) that aren't
# represented among the top dataset titles. Appended after the
# dataset-derived examples.
EXTRA_EXAMPLES = [
    "7 min warm-up, 10 x 1 min hard / 1 min light, 3 min cool-down",
    "6 minutes easy, 1 minute rest, 1 minute hard, 1 minute rest, 1 minute "
    "hard, 1 minute rest, 1 minute hard, 1 minute rest, 1 minute hard, 1 "
    "minute rest, 1 minute hard, 1 minute rest, 1 minute hard, 1 minute "
    "rest, 1 minute hard, 1 minute rest, 1 minute hard, 1 minute rest, 1 "
    "minute hard, 1 minute rest, 1 minute hard, 1 minute rest, 3 minutes "
    "easy",
]


def load_top_titles(dataset_path: str, n: int) -> list[str]:
    """Return the top n titles by count from dataset_path, restricted
    to rows whose 'machines' field is in _ROWERG_MACHINES."""
    rows = []
    with open(dataset_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            row = json.loads(line)
            if row.get("machines") in _ROWERG_MACHINES:
                rows.append((row["count"], row["title"]))

    rows.sort(key=lambda pair: (-pair[0], pair[1]))
    return [title for _count, title in rows[:n]]


def write_examples_js(titles: list[str], out_path: str) -> None:
    lines = [
        "// Generated by web/build_examples.py from data/dataset_unique.jsonl.",
        "// Do not edit by hand -- re-run the script instead.",
        "const PM5KEYS_EXAMPLES = " + json.dumps(titles, indent=2) + ";",
        "",
    ]
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset", default=_DEFAULT_DATASET)
    parser.add_argument("--out", default=_DEFAULT_OUT)
    parser.add_argument("-n", type=int, default=8)
    args = parser.parse_args(argv)

    titles = load_top_titles(args.dataset, args.n) + EXTRA_EXAMPLES
    write_examples_js(titles, args.out)
    print(f"wrote {len(titles)} example titles to {args.out}")
    for title in titles:
        print(f"  - {title}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
